# --------------------------------------------------
# Site Settings
# --------------------------------------------------

# Menu  用 || 将内容分割为两部分，前面部分为页面 URL，后面部分为菜单中显示的名称. 
# 对于系统默认页面，如 归档（/archives）、首页（/） 等，直接添加菜单即可；对于独立页面，如 标签（tags）、分类（categories），则需先创建页面后再添加菜单。
menu:
  home: / || 首页
  galleries: /galleries/ || 摄影
  archives: /archives/ || 归档
  tags: /tags/ || 标签
  categories: /categories/ || 分类
  about: /about/ || 关于

# Color 主题颜色
color:
  text: '#33333D'
  text-secondary: '#4e4e4e'
  text-third: '#999999'
  background: '#ffffff'
  background-secondary: '#f6f8fa'
  border: '#eeeeee'
  text-dark: '#dddddd'
  text-secondary-dark: '#9899ab'
  text-third-dark: '#7d8594'
  background-dark: '#1e2128'
  background-secondary-dark: '#1a1d22'
  border-dark: '#2b3038'
  link: '#FF3B00'

# Favicon 站点图标 配置项 favicon 可设置站点图标，建议使用 ico 或 png 格式
favicon:
  small: /images/icons/favicon-16x16.png
  medium: /images/icons/favicon-32x32.png
  apple_touch_icon: /images/icons/apple-touch-icon.png
  safari_pinned_tab: /images/icons/stun-logo.svg
  msapplication: /images/icons/favicon-144x144.png

# Font 全局字体 
font:
  size: 14px # 字体大小
  # family: 'Hiragino Sans GB', 'Hiragino Sans GB W3', 'Microsoft YaHei', 'WenQuanYi Micro Hei', sans-serif
  family:

# Background Image 背景图片  建议纯白挺好看
background_image:

# Loading 配置项 loading 可设置载入动画，会在 页面跳转、懒加载 时加载，目前仅支持图片形式
loading: 
  light: /images/theme/loading.gif
  dark: /images/theme/loading.gif

# Preview 配置项 preview 中的一些列配置可自定义欢迎页面
preview:
  enable: true  # 用来 开启 / 关闭 欢迎页面
  type: wave  # wave | cloud   # 效果模式wave波浪  cloud云层
  background: # 设置欢迎图片
    type: image # image video 图片或视频
    default_image: # 配置静态图片，填写静态图片 URL 即可。开启 深色模式 后支持配置 深色/浅色 两种模式下的背景图片。
      light: /images/theme/welcome_light_2.jpg
      dark: /images/theme/welcome_dark_1.jpg
    video: #配置动态视频，填写视频 URL 即可。
    api: # https://source.unsplash.com/random/1920x1080  # 配置随机图片，可使用第三方 API，优先级 随机图片（api） > 静态图片（default）。推荐 API：Unsplash、必应图片。
    size: cover # css: background-size 设置图片尺寸
    position: center # css: background-position  设置图片位置
  motto: # 格言
    default: 我在开了灯的床头下，想问问自己的心啊。   # 配置静态格言
    color: '#ffffff'
    typing: true
    api: https://v2.jinrishici.com/one.json #  配置随机格言，可使用第三方 API，优先级 随机格言（api） > 静态格言（default）。推荐 API：一言、今日诗词。
    data_contents: ['data', 'content']
    # ex.one  =>  apl: https://v1.hitokoto.cn/?encode=text&c=i  data_contents:
    # ex.two  =>  api: https://v2.jinrishici.com/one.json  data_contents: ['data', 'content']

# Navbar
navbar:
  enable: true  # 用于控制头部导航条全局显示/隐藏
  back_home: true # 用于开启返回首页按钮；其余的功能按钮随各自配置开启，例如“二维码”、“黑夜模式”、“搜索”等。

# Copyright # 版权信息
copyright: <p><a target="_blank" href="https://beian.miit.gov.cn">津ICP备2021000046号-1</a></p>

# Social 社交链接 配置内容分为三部分，以 || 划分。第一部分是 社交链接 ，第二部分是 图标样式（IconFont） ，第三部分是 选中颜色（hover）。
social:
  qq: tencent://message/?Menu=yes&uin=156794426 || iconQQ || '#12B7F5'
  wechat: javascript:; || iconwechat-fill || '#09BB07'
  instagram: https://github.com/AshaoSunshine || iconinstagram || '#DA2E76'
  github: https://github.com/AshaoSunshine || icongithub-fill || '#9f7be1'
  email: https://mail.163.com/ || iconmail || '#4e4e4e'

# Override Scrollbar
scrollbar:
  type: default # default | simple | normal | none

# Fab (Float Action Button) 配置项 fab 用于配置右下角的按钮
fab:
  enable: true # 设置开启/关闭按钮
  always_show: false # 设置一直显示/过度隐藏按钮

# Search
search:
  enable: true

# QR Code 配置项 qrcode 用来设置 二维码，开启后点击 导航栏 左侧的图标即可显示。
qrcode:
  enable: false  # 设置 开启 / 关闭 二维码功能。
  type: url # url | image  设置二维码模式，有两种模式可选。url 显示当前文章链接生成的二维码；image 显示固定的二维码图片（如小程序码等）。
  image: https://pic.izhaoo.com/weapp-code.jpg  # 选择 image 模式时需要指定图片链接。

# Color Mode 深色模式设置
color_mode:
  enable: true

# Gray (Mourning Mode) 哀悼模式
gray:
  enable: false

excerpt_description: true
# --------------------------------------------------
# Post Settings
# --------------------------------------------------

# Post Image 默认封面 配置项 post_image 设置配置文章默认封面，就不用为每篇文章单独设置封面了：
post_image:
  random: local # local galleries 设置随机封面，有 galleries（相册图库） 和 local（本地图库） 两种模式。开启 相册 功能后会自动调取相册中的图片；本地图库需要新建 /_data/local_images.json 文件，填写图片 URL 列表即可。
  default: /images/theme/post-image.jpg # 未设置随机封面时启用 默认封面，填写图片 URL 即可。

# Page Size 文章尺寸
post_page_size:
  width: 800px # 设置内容宽度

# Caption 设置图片标注
caption:
  enable: true # 开启关闭

# 
local_search:
  enable: true

# Indent
indent:
  content:
  excerpt:

# TOC 配置项 toc 用于设置 文章目录，开启后会在文章内容右侧生成目录，点击目录可平滑到对应的标题处。
toc:
  enable: true
  always_show: true
  min_depth: 1
  max_depth: 3

# Donate 配置项 donate 用于设置 打赏二维码，开启后可在文章下方展示二维码，扫一扫请博主喝杯咖啡吧~
donate:
  enable: false
  alipay: https://pic.izhaoo.com/alipay.jpg
  wechat: https://pic.izhaoo.com/wechat.jpg

# Copyright 配置项 post_copyright 用于设置 文章版权，开启后可在文章下方展示版权信息。
post_copyright:
  enable: true

# Carrier（copy article with one click）
carrier:
  enable: true
  type: html # html | markdown | text

# --------------------------------------------------
# Page Settings
# --------------------------------------------------

# Galleries
galleries:
  enable: true  #开启 / 关闭 相册功能。
  title: 摄影 # 相册分类页面标题
  subtitle: Photography # 相册分类页面副标题。
  type: waterfall # waterfall | grid  #相册显示风格，有 瀑布流 和 正方形 两种形式。
  columns: 3 # 相册列数


# --------------------------------------------------
# Comment Settings
# --------------------------------------------------

comments:
  enable: false
  type: valine # gitalk | valine | changyan
  button: true

# Gitalk
gitalk:
  owner:
  repo:
  admin:
  clientID:
  clientSecret:

# Valine
valine:
  appId:
  appKey:
  placeholder: 雁过留痕
  avatar: mp
  pageSize: 10
  lang: zh-CN

# ChangYan
changyan:
  appId:
  conf:

# --------------------------------------------------
# Plugin settings
# --------------------------------------------------

# Notification
notification:
  enable: false
  delay: 4500
  page_white_list:
  page_black_list:

# Daovoice
daovoice:
  enable: false
  appId: # app_id

# Tencent Chao
tencentChao:
  enable: false
  appId: # app_id

# LeanCloud
leancloud:
  enable: false
  appId:
  appKey:
  serverURLs: https://leancloud.cn/

# Lazyload
lazyload:
  enable: true
  only_post: false
  loading: 
    light: /images/theme/loading.gif
    dark: /images/theme/loading.gif

# FancyBox
fancybox: true

# Pjax
pjax: true

# HighLight
highlight:
  enable: true
  style: # https://highlightjs.org/static/demo/
    light: Xcode
    dark: Solarized Dark

# SEO
seo:
  baidu_auto_push: true

# Analytics
analytics:
  baidu:  # id
  google: # id
  tencent: # id
  cnzz: # id

# --------------------------------------------------
# Script Settings
# --------------------------------------------------

# CDN
vendors:
  jquery_js: https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js
  fancybox_js: https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js
  pjax_js: https://cdn.bootcss.com/jquery.pjax/2.0.1/jquery.pjax.min.js
  lazyload_js: https://cdn.bootcdn.net/ajax/libs/jquery.lazyload/1.9.1/jquery.lazyload.min.js
  qrcode_js: https://cdn.bootcdn.net/ajax/libs/jquery.qrcode/1.0/jquery.qrcode.min.js
  daovoice_js: https://widget.daovoice.io/widget/0f81ff2f.js
  fancybox_css: https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css
  highlight_css: https://cdn.bootcss.com/highlight.js/9.18.1/styles/
  iconfont_css: //at.alicdn.com/t/font_1445822_r673sha78lq.css

# Custom
custom:
  head:
  foot:
  css:
  js:
